version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=nz4oAfNqOHqrS8hd1t9o
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PGUSER=postgres
      - PGHOST=containers-us-west-20.railway.app
      - PGDATABASE=railway,
      - PGPASSWORD=nz4oAfNqOHqrS8hd1t9o
      - PGPORT=7757
  frontend:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app